
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 28 20:21:44 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTBRACKET = 6;
  public static final int DIVIDE = 30;
  public static final int INCREMENT = 41;
  public static final int CONST = 13;
  public static final int NAMESPACE = 5;
  public static final int NUMCONSTANT = 48;
  public static final int RIGHTPAREN = 9;
  public static final int RIGHTBRACKET = 7;
  public static final int NOTEQUAL = 22;
  public static final int CONTINUE = 36;
  public static final int GREATER = 23;
  public static final int DECREMENT = 42;
  public static final int FOR = 40;
  public static final int LESS = 25;
  public static final int MINUS = 28;
  public static final int LEFTPAREN = 8;
  public static final int STATIC = 12;
  public static final int AND = 43;
  public static final int SEMICOLON = 10;
  public static final int LESSEQUAL = 26;
  public static final int OR = 44;
  public static final int COMMA = 11;
  public static final int CLASS = 16;
  public static final int BOOLCONSTANT = 49;
  public static final int PLUS = 27;
  public static final int MULTIPLY = 29;
  public static final int IF = 33;
  public static final int IDENTIFICATOR = 46;
  public static final int DOT = 18;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int EQUAL = 20;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int ISEQUAL = 21;
  public static final int PROGRAM = 2;
  public static final int CHARCONSTANT = 47;
  public static final int BREAK = 35;
  public static final int VOID = 14;
  public static final int GREATEREQUAL = 24;
  public static final int ARROW = 19;
  public static final int COLON = 45;
  public static final int RIGHTBRACE = 4;
  public static final int ELSE = 34;
  public static final int READ = 38;
  public static final int LEFTBRACE = 3;
  public static final int EXTENDS = 17;
  public static final int MODUO = 31;
  public static final int PRINT = 39;
  public static final int DOUBLECOLON = 32;
}

