
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 27 22:55:38 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTBRACKET = 5;
  public static final int DIVIDE = 31;
  public static final int INCREMENT = 42;
  public static final int CONST = 13;
  public static final int NUMCONSTANT = 53;
  public static final int RIGHTPAREN = 8;
  public static final int RIGHTBRACKET = 6;
  public static final int NOTEQUAL = 23;
  public static final int CONTINUE = 37;
  public static final int GREATER = 24;
  public static final int DECREMENT = 43;
  public static final int FOR = 41;
  public static final int LESS = 26;
  public static final int MINUS = 29;
  public static final int LEFTPAREN = 7;
  public static final int STATIC = 11;
  public static final int AND = 44;
  public static final int SEMICOLON = 9;
  public static final int RANGE = 12;
  public static final int LESSEQUAL = 27;
  public static final int OR = 45;
  public static final int IN = 20;
  public static final int COMMA = 10;
  public static final int CLASS = 16;
  public static final int BOOLCONSTANT = 54;
  public static final int PLUS = 28;
  public static final int MULTIPLY = 30;
  public static final int IF = 34;
  public static final int IDENTIFICATOR = 51;
  public static final int DOT = 18;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int EQUAL = 21;
  public static final int INCDOBL = 47;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int ISEQUAL = 22;
  public static final int PROGRAM = 2;
  public static final int CHARCONSTANT = 52;
  public static final int BREAK = 36;
  public static final int VOID = 14;
  public static final int GREATEREQUAL = 25;
  public static final int ARROW = 19;
  public static final int COLON = 46;
  public static final int RIGHTBRACE = 4;
  public static final int SUSEDI = 49;
  public static final int ELSE = 35;
  public static final int READ = 39;
  public static final int LEFTBRACE = 3;
  public static final int EXTENDS = 17;
  public static final int SUM = 50;
  public static final int OPERATOR = 48;
  public static final int MODUO = 32;
  public static final int PRINT = 40;
  public static final int DOUBLECOLON = 33;
}

